import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";

const API=import.meta.env.VITE_API_URL??"https://morok-ai.onrender.com";
type Msg={role:"user"|"assistant";content:string};
function App(){
 const[token,setToken]=useState(localStorage.getItem("morok_token")??"");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[input,setInput]=useState("");const[messages,setMessages]=useState<Msg[]>([]);const[loading,setLoading]=useState(false);const[status,setStatus]=useState("OFFLINE");const[listening,setListening]=useState(false);const[tab,setTab]=useState("chat");const[notice,setNotice]=useState("");
 const speech=useMemo(()=>{const C=window.SpeechRecognition??window.webkitSpeechRecognition;return C?new C():null},[]);
 useEffect(()=>{fetch(API+"/health").then(r=>setStatus(r.ok?"ONLINE":"OFFLINE")).catch(()=>setStatus("OFFLINE"));},[]);
 useEffect(()=>()=>{speech?.stop()},[speech]);
 async function auth(path:string){setLoading(true);try{const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Falha");localStorage.setItem("morok_token",d.token);setToken(d.token);setNotice("Acesso autorizado");}catch(e){setNotice(e instanceof Error?e.message:"Falha")}finally{setLoading(false)}}
 async function send(text=input){if(!text.trim()||!token)return;setMessages(m=>[...m,{role:"user",content:text}]);setInput("");setLoading(true);try{const r=await fetch(API+"/api/v1/messages",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Falha de comunicação");setMessages(m=>[...m,{role:"assistant",content:d.content}]);}catch(e){setNotice(e instanceof Error?e.message:"Falha")}finally{setLoading(false)}}
 function startVoice(){if(!speech){setNotice("Reconhecimento de voz não suportado neste navegador");return}speech.lang="pt-BR";speech.continuous=false;speech.interimResults=false;speech.onstart=()=>setListening(true);speech.onend=()=>setListening(false);speech.onresult=(e: any)=>{const text=e.results[0]?.[0]?.transcript??"";setInput(text);void send(text)};speech.start()}
 function logout(){localStorage.removeItem("morok_token");setToken("");setMessages([])}
 if(!token)return <main className="shell"><section className="login"><div className="brand">MOROK</div><div className="eyebrow">PERSONAL INTELLIGENCE SYSTEM</div><h1>Entre no seu núcleo.</h1><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Senha"/><div className="row"><button onClick={()=>void auth("/api/v1/auth/login")} disabled={loading}>ENTRAR</button><button className="ghost" onClick={()=>void auth("/api/v1/auth/register")} disabled={loading}>CRIAR CONTA</button></div><p className="hint">{notice||"Seu ambiente pessoal do Morok."}</p></section></main>;
 return <main className="shell"><aside><div className="brand">MOROK</div><div className="side-status"><i/> {status}</div><nav>{["chat","tasks","memory","files","calendar","settings"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x==="chat"?"CONVERSA":x==="tasks"?"TAREFAS":x==="memory"?"MEMÓRIA":x==="files"?"ARQUIVOS":x==="calendar"?"AGENDA":"CONFIGURAÇÕES"}</button>)}</nav><button className="logout" onClick={logout}>SAIR</button></aside><section className="workspace"><header><div><span className="eyebrow">MOROK CORE / PHASE 1</span><h2>{tab==="chat"?"CONVERSA":"CENTRAL "+tab.toUpperCase()}</h2></div><div className="status">{status}</div></header>{tab==="chat"?<><div className="messages">{messages.length===0&&<div className="empty"><span className="orb"/> <strong>Morok online.</strong><small>Envie uma instrução, pergunta ou comando.</small></div>}{messages.map((m,i)=><article className={m.role} key={i}><span>{m.role==="user"?"VOCÊ":"MOROK"}</span><p>{m.content}</p></article>)}</div><form onSubmit={e=>{e.preventDefault();void send()}}><button type="button" className={listening?"mic activeMic":"mic"} onClick={startVoice}>◉</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder={loading?"Processando...":"Digite uma instrução..."}/><button disabled={loading||!input.trim()}>ENVIAR</button></form></>:<div className="module"><p>O módulo <b>{tab}</b> está conectado ao núcleo. Use a conversa para operar seus recursos ou continue pela API autenticada.</p>{notice&&<small>{notice}</small>}</div>}</section></main>
}
declare global{interface Window{SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any}}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
