import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const API=import.meta.env.VITE_API_URL??"https://morok-ai.onrender.com";
type Msg={role:"user"|"assistant";content:string};
type Task={id:string;title:string;status:string;dueAt?:string};
type Memory={id:string;content:string};
type Doc={id:string;name:string;format:string;content?:string};
type Event={id:string;title:string;startsAt:string;endsAt?:string;notes?:string};
function App(){
 const[token,setToken]=useState(localStorage.getItem("morok_token")??"");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[input,setInput]=useState("");const[messages,setMessages]=useState<Msg[]>([]);const[loading,setLoading]=useState(false);const[status,setStatus]=useState("OFFLINE");const[listening,setListening]=useState(false);const[speaking,setSpeaking]=useState(true);const[tab,setTab]=useState("chat");const[notice,setNotice]=useState("");const[conversationId,setConversationId]=useState(localStorage.getItem("morok_conversation")??"");const[tasks,setTasks]=useState<Task[]>([]);const[events,setEvents]=useState<Event[]>([]);const[memories,setMemories]=useState<Memory[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[secretCount,setSecretCount]=useState(0);const[contacts,setContacts]=useState<any[]>([]);const[notifications,setNotifications]=useState<any[]>([]);const[automations,setAutomations]=useState<any[]>([]);const[integrations,setIntegrations]=useState<any[]>([]);const[files,setFiles]=useState<any[]>([]);
 const speech=useMemo(()=>{const C=window.SpeechRecognition??window.webkitSpeechRecognition;return C?new C():null},[]);
 useEffect(()=>{fetch(API+"/health").then(r=>setStatus(r.ok?"ONLINE":"OFFLINE")).catch(()=>setStatus("OFFLINE"));},[]);
 useEffect(()=>()=>{speech?.stop();window.speechSynthesis?.cancel()},[speech]);
 async function request(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{}),...(init.headers??{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"request_failed");return d}
 async function auth(path:string){setLoading(true);try{const d=await request(path,{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("morok_token",d.token);setToken(d.token);setNotice("Acesso autorizado");}catch(e){setNotice(e instanceof Error?e.message:"Falha")}finally{setLoading(false)}}
 async function loadConversation(){if(!conversationId)return;try{const d=await request("/api/v1/conversations/"+conversationId);setMessages((d.conversation.messages??[]).filter((m:any)=>m.role==="user"||m.role==="assistant").map((m:any)=>({role:m.role,content:m.content})))}catch{}}
 async function loadData(){try{const[t,cal,m,d,v,c,n,a,i,fl]=await Promise.all([request("/api/v1/tasks"),request("/api/v1/calendar"),request("/api/v1/memories"),request("/api/v1/documents"),request("/api/v1/vault"),request("/api/v1/contacts"),request("/api/v1/notifications"),request("/api/v1/automations"),request("/api/v1/integrations"),request("/api/v1/files")]);setTasks(t.tasks??[]);setEvents(cal.events??[]);setMemories(m.memories??[]);setDocs(d.documents??[]);setSecretCount((v.secrets??[]).length);setContacts(c.contacts??[]);setNotifications(n.notifications??[]);setAutomations(a.automations??[]);setIntegrations(i.integrations??[]);setFiles(fl.files??[])}catch(e){setNotice(e instanceof Error?e.message:"Falha ao carregar dados")}}
 useEffect(()=>{if(token){void loadConversation();void loadData()}},[token]);
 async function send(text=input){if(!text.trim()||!token||loading)return;const value=text.trim();setInput("");setMessages(m=>[...m,{role:"user",content:value},{role:"assistant",content:""}]);setLoading(true);try{const params=new URLSearchParams({message:value,...(conversationId?{conversationId}:{})});const r=await fetch(API+"/api/v1/messages/stream?"+params.toString(),{headers:{Authorization:`Bearer ${token}`}});if(!r.ok||!r.body)throw new Error("stream_failed");const reader=r.body.getReader();const decoder=new TextDecoder();let buffer="";let full="";for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.startsWith("data: "))continue;const payload=line.slice(6);if(payload==="[DONE]")continue;try{const d=JSON.parse(payload);if(d.conversationId&&!conversationId){setConversationId(d.conversationId);localStorage.setItem("morok_conversation",d.conversationId)}if(d.chunk){full+=d.chunk;setMessages(m=>{const copy=[...m];copy[copy.length-1]={role:"assistant",content:full};return copy})}}catch{}}}if(speaking&&full)window.speechSynthesis?.speak(new SpeechSynthesisUtterance(full));}catch(e){setNotice(e instanceof Error?e.message:"Falha de comunicação");setMessages(m=>m.slice(0,-1))}finally{setLoading(false)}}
 function startVoice(){if(!speech){setNotice("Reconhecimento de voz não suportado neste navegador");return}speech.lang="pt-BR";speech.continuous=false;speech.interimResults=false;speech.onstart=()=>setListening(true);speech.onend=()=>setListening(false);speech.onresult=(e:any)=>{const text=e.results[0]?.[0]?.transcript??"";setInput(text);void send(text)};speech.start()}
 async function addTask(){const title=window.prompt("Título da tarefa");if(!title)return;try{const d=await request("/api/v1/tasks",{method:"POST",body:JSON.stringify({title})});setTasks(x=>[d.task,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function completeTask(id:string){try{await request("/api/v1/tasks/"+id+"/complete",{method:"POST"});setTasks(x=>x.map(t=>t.id===id?{...t,status:"completed"}:t))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addEvent(){const title=window.prompt("Título do evento");if(!title)return;const startsAt=window.prompt("Início (ISO 8601)","2030-01-01T10:00:00.000Z");if(!startsAt)return;try{const d=await request("/api/v1/calendar",{method:"POST",body:JSON.stringify({title,startsAt})});setEvents(x=>[...x,d.event].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addContact(){const name=window.prompt("Nome do contato");if(!name)return;try{const d=await request("/api/v1/contacts",{method:"POST",body:JSON.stringify({name,email:window.prompt("E-mail")??undefined,phone:window.prompt("Telefone")??undefined})});setContacts(x=>[...x,d.contact].sort((a,b)=>a.name.localeCompare(b.name)))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addNotification(){const content=window.prompt("Notificação");if(!content)return;try{const d=await request("/api/v1/notifications",{method:"POST",body:JSON.stringify({content})});setNotifications(x=>[d.notification,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addAutomation(){const name=window.prompt("Nome da automação");if(!name)return;const type=window.prompt("Gatilho: interval ou at","interval");if(type!=="interval"&&type!=="at")return;const value=window.prompt(type==="interval"?"Intervalo em segundos":"Data/hora ISO");if(!value)return;const actionType=window.prompt("Ação: notification.create ou task.create","notification.create");if(actionType!=="notification.create"&&actionType!=="task.create")return;const content=window.prompt(actionType==="task.create"?"Título da tarefa":"Conteúdo da notificação");if(!content)return;try{const d=await request("/api/v1/automations",{method:"POST",body:JSON.stringify({name,trigger:{type,value},action:{type:actionType,input:actionType==="task.create"?{title:content}:{content}}})});setAutomations(x=>[d.automation,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function toggleAutomation(a:any){try{const d=await request("/api/v1/automations/"+a.id,{method:"PATCH",body:JSON.stringify({enabled:!a.enabled})});setAutomations(x=>x.map(v=>v.id===a.id?d.automation:v))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addSecret(){const name=window.prompt("Nome da credencial");if(!name)return;const value=window.prompt("Valor secreto");if(!value)return;try{const d=await request("/api/v1/vault",{method:"POST",body:JSON.stringify({name,value,kind:"credential"})});setSecretCount(x=>x+1);setNotice("Credencial armazenada")}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function toggleIntegration(a:any){try{const d=await request("/api/v1/integrations/"+a.id,{method:"PATCH",body:JSON.stringify({enabled:!a.enabled})});setIntegrations(x=>x.map(v=>v.id===a.id?d.integration:v))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addIntegration(){const name=window.prompt("Nome da integração");if(!name)return;const endpoint=window.prompt("Endpoint HTTPS");if(!endpoint)return;const secret=window.prompt("Bearer/token");if(!secret)return;try{const d=await request("/api/v1/integrations",{method:"POST",body:JSON.stringify({name,endpoint,secret,type:"webhook"})});setIntegrations(x=>[d.integration,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addFile(){const name=window.prompt("Nome do arquivo");if(!name)return;const content=window.prompt("Conteúdo do arquivo","")??"";try{const d=await request("/api/v1/files",{method:"POST",body:JSON.stringify({name,mimeType:"text/plain",contentBase64:btoa(unescape(encodeURIComponent(content)))})});setFiles(x=>[d.file,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function deleteFile(id:string){try{await request("/api/v1/files/"+id,{method:"DELETE"});setFiles(x=>x.filter(v=>v.id!==id))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function deleteDoc(id:string){try{await request("/api/v1/documents/"+id,{method:"DELETE"});setDocs(x=>x.filter(v=>v.id!==id))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addMemory(){const content=window.prompt("Memória");if(!content)return;try{const d=await request("/api/v1/memories",{method:"POST",body:JSON.stringify({content})});setMemories(x=>[d.memory,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function addDoc(){const name=window.prompt("Nome do documento","novo.md");if(!name)return;const content=window.prompt("Conteúdo","")??"";try{const d=await request("/api/v1/documents",{method:"POST",body:JSON.stringify({name,format:name.endsWith(".json")?"json":name.endsWith(".csv")?"csv":name.endsWith(".html")?"html":name.endsWith(".txt")?"text":"markdown",content})});setDocs(x=>[d.document,...x])}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 async function openDoc(id:string){try{const d=await request("/api/v1/documents/"+id);const next=window.prompt("Editar documento",d.document.content);if(next===null)return;const u=await request("/api/v1/documents/"+id,{method:"PATCH",body:JSON.stringify({content:next})});setDocs(x=>x.map(v=>v.id===id?u.document:v))}catch(e){setNotice(e instanceof Error?e.message:"Falha")}}
 function logout(){localStorage.removeItem("morok_token");setToken("");setMessages([])}
 if(!token)return <main className="shell"><section className="login"><div className="brand">MOROK</div><div className="eyebrow">PERSONAL INTELLIGENCE SYSTEM</div><h1>Entre no seu núcleo.</h1><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Senha"/><div className="row"><button onClick={()=>void auth("/api/v1/auth/login")} disabled={loading}>ENTRAR</button><button className="ghost" onClick={()=>void auth("/api/v1/auth/register")} disabled={loading}>CRIAR CONTA</button></div><p className="hint">{notice||"Seu ambiente pessoal do Morok."}</p></section></main>;
 const labels:any={chat:"CONVERSA",tasks:"TAREFAS",memory:"MEMÓRIA",files:"ARQUIVOS",documents:"DOCUMENTOS",calendar:"AGENDA",contacts:"CONTATOS",notifications:"NOTIFICAÇÕES",automations:"AUTOMAÇÕES",integrations:"INTEGRAÇÕES",vault:"COFRE",settings:"CONFIGURAÇÕES"};
 return <main className="shell"><aside><div className="brand">MOROK</div><div className="side-status"><i/> {status}</div><nav>{Object.keys(labels).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{labels[x]}</button>)}</nav><button className="logout" onClick={logout}>SAIR</button></aside><section className="workspace"><header><div><span className="eyebrow">MOROK CORE / PHASE 1</span><h2>{labels[tab]}</h2></div><div className="status">{status}</div></header>{tab==="chat"&&<><div className="messages">{messages.length===0&&<div className="empty"><span className="orb"/> <strong>Morok online.</strong><small>Conversa persistente, streaming e voz.</small></div>}{messages.map((m,i)=><article className={m.role} key={i}><span>{m.role==="user"?"VOCÊ":"MOROK"}</span><p>{m.content||"…"}</p></article>)}</div><form onSubmit={e=>{e.preventDefault();void send()}}><button type="button" className={listening?"mic activeMic":"mic"} onClick={startVoice}>◉</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder={loading?"Transmitindo...":"Digite uma instrução..."}/><button disabled={loading||!input.trim()}>ENVIAR</button></form></>}
 {tab==="tasks"&&<Module title="Tarefas" action={addTask}>{tasks.map(t=><div className="item" key={t.id}><b>{t.title}</b><span>{t.status}</span>{t.status==="pending"&&<button onClick={()=>void completeTask(t.id)}>concluir</button>}</div>)}</Module>}
 {tab==="memory"&&<Module title="Memória" action={addMemory}>{memories.map(m=><div className="item" key={m.id}><span>{m.content}</span></div>)}</Module>}
 {tab==="files"&&<Module title="Arquivos" action={addFile}>{files.map(f=><div className="item" key={f.id}><b>{f.name}</b><span>{f.mimeType}</span><button onClick={()=>void deleteFile(f.id)}>excluir</button></div>)}</Module>}
 {tab==="documents"&&<Module title="Documentos" action={addDoc}>{docs.map(d=><div className="item" key={d.id}><b>{d.name}</b><span>{d.format}</span><button onClick={()=>void openDoc(d.id)}>abrir/editar</button><button onClick={()=>void deleteDoc(d.id)}>excluir</button></div>)}</Module>}
 {tab==="calendar"&&<Module title="Agenda" action={addEvent}>{events.map(e=><div className="item" key={e.id}><b>{e.title}</b><span>{new Date(e.startsAt).toLocaleString("pt-BR")}</span></div>)}</Module>}
 {tab==="contacts"&&<Module title="Contatos" action={addContact}>{contacts.map(c=><div className="item" key={c.id}><b>{c.name}</b><span>{c.email??""} {c.phone??""}</span></div>)}</Module>}
 {tab==="notifications"&&<Module title="Notificações" action={addNotification}>{notifications.map(n=><div className="item" key={n.id}><span>{n.content}</span><small>{new Date(n.createdAt).toLocaleString("pt-BR")}</small></div>)}</Module>}
 {tab==="automations"&&<Module title="Automações" action={addAutomation}>{automations.map(a=><div className="item" key={a.id}><b>{a.name}</b><span>{a.trigger.type}:{a.trigger.value}</span><button onClick={()=>void toggleAutomation(a)}>{a.enabled?"desativar":"ativar"}</button></div>)}</Module>}
 {tab==="integrations"&&<Module title="Integrações" action={addIntegration}>{integrations.map(a=><div className="item" key={a.id}><b>{a.name}</b><span>{a.type}</span><button onClick={()=>void toggleIntegration(a)}>{a.enabled?"desativar":"ativar"}</button></div>)}</Module>}
 {tab==="vault"&&<Module title="Cofre" action={addSecret}><div className="item"><b>{secretCount}</b><span>credenciais protegidas por criptografia.</span></div></Module>}
 {tab==="settings"&&<Module title="Configurações"><div className="item"><b>Voz</b><button onClick={()=>setSpeaking(x=>!x)}>{speaking?"TTS ligado":"TTS desligado"}</button></div><div className="item"><b>Cofre</b><span>{secretCount} credenciais armazenadas com criptografia.</span></div><div className="item"><b>Conversa</b><button onClick={()=>{localStorage.removeItem("morok_conversation");setConversationId("");setMessages([])}}>nova conversa</button></div><small>{notice}</small></Module>}</section></main>
}
function Module(p:{title:string;action?:()=>void;children:React.ReactNode}){return <div className="module"><div className="moduleHead"><h3>{p.title}</h3>{p.action&&<button onClick={p.action}>NOVO</button>}</div>{p.children}</div>}
declare global{interface Window{SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any}}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
