import { randomUUID } from "node:crypto";
import type { Db } from "mongodb";
export interface Automation { id:string; userId:string; name:string; trigger:{type:"interval"|"at";value:string}; action:{type:string;input:Record<string,unknown>}; enabled:boolean; lastRunAt?:Date; createdAt:Date; updatedAt:Date }
export class AutomationService {
 constructor(private readonly db:Db){}
 async create(userId:string,name:string,trigger:Automation["trigger"],action:Automation["action"]){if(trigger.type==="interval"&&(Number(trigger.value)<=0||!Number.isFinite(Number(trigger.value))))throw new Error("invalid_interval");if(trigger.type==="at"&&Number.isNaN(new Date(trigger.value).getTime()))throw new Error("invalid_schedule");const now=new Date();const item:Automation={id:randomUUID(),userId,name:name.trim(),trigger,action,enabled:true,createdAt:now,updatedAt:now};await this.db.collection<Automation>("automations").insertOne(item);return item;}
 async list(userId:string){return this.db.collection<Automation>("automations").find({userId}).sort({createdAt:-1}).limit(100).toArray();}
 async setEnabled(userId:string,id:string,enabled:boolean){return this.db.collection<Automation>("automations").findOneAndUpdate({id,userId},{$set:{enabled,updatedAt:new Date()}},{returnDocument:"after"});}
 async runDue(executor:(automation:Automation)=>Promise<void>){const now=new Date();const rows=await this.db.collection<Automation>("automations").find({enabled:true}).limit(1000).toArray();for(const a of rows){const last=a.lastRunAt?.getTime()??0;let due=false;if(a.trigger.type==="at")due=now.getTime()>=new Date(a.trigger.value).getTime()&&last===0;else due=now.getTime()-last>=Number(a.trigger.value)*1000;if(!due)continue;try{await executor(a);await this.db.collection("automations").updateOne({id:a.id},{$set:{lastRunAt:now,updatedAt:now}});await this.db.collection("audit_logs").insertOne({action:"automation.completed",actorId:a.userId,automationId:a.id,createdAt:now});if(a.trigger.type==="at")await this.db.collection("automations").updateOne({id:a.id},{$set:{enabled:false}});}catch(error){await this.db.collection("audit_logs").insertOne({action:"automation.failed",actorId:a.userId,automationId:a.id,error:error instanceof Error?error.message:"unknown",createdAt:new Date()});}}}
}