import assert from "node:assert/strict";
import test from "node:test";
import { EventBus } from "./bus.js";
import { SessionService } from "./session.js";
import { ToolRegistry } from "./tools.js";
import { requiresConfirmation } from "./permissions.js";
test("event bus dispatches events",async()=>{const bus=new EventBus();let called=false;bus.on("system.alert",async()=>{called=true});await bus.emit("system.alert",{ok:true});assert.equal(called,true)});
test("session service creates sessions",()=>{const s=new SessionService().create("user-1");assert.equal(s.userId,"user-1");assert.ok(s.id)});
test("tool registry stores tools",()=>{const r=new ToolRegistry();r.register({id:"x",name:"X",description:"X"});assert.equal(r.list().length,1)});
test("critical permissions require confirmation",()=>{assert.equal(requiresConfirmation("tool.execute"),true);assert.equal(requiresConfirmation("conversation.read"),false)});