import { config } from "../config.js";
import dns from "node:dns/promises";
import net from "node:net";
function blockedHost(host:string):boolean{const h=host.toLowerCase().replace(/^\[|\]$/g,"");if(h==="localhost"||h.endsWith(".localhost")||h==="metadata.google.internal")return true;if(net.isIP(h)){if(h.includes(":"))return true;const p=h.split(".").map(Number);const a=p[0]??-1,b=p[1]??-1;if(p.length===4&&(a===10||a===127||(a===169&&b===254)||(a===192&&b===168)||(a===172&&b>=16&&b<=31)))return true;}return false;}
async function assertSafeUrl(raw:string):Promise<URL>{const url=new URL(raw.startsWith("www.")?"https://"+raw:raw);if(!["http:","https:"].includes(url.protocol))throw new Error("unsupported_url_protocol");if(blockedHost(url.hostname))throw new Error("blocked_private_url");try{const addresses=await dns.lookup(url.hostname,{all:true});if(addresses.some(a=>blockedHost(a.address)))throw new Error("blocked_private_url");}catch(e){if(e instanceof Error&&e.message==="blocked_private_url")throw e;}return url;}
function stripHtml(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\s+/g," ").trim();}
export interface WebResult{url:string;title:string;text:string}
export class WebService{
 async open(rawUrl:string):Promise<WebResult>{let current=await assertSafeUrl(rawUrl);for(let i=0;i<5;i++){const response=await fetch(current,{redirect:"manual",signal:AbortSignal.timeout(config.webTimeoutMs),headers:{"user-agent":"Morok/1.0"}});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new Error("web_redirect_missing");current=await assertSafeUrl(new URL(location,current).toString());continue;}if(!response.ok)throw new Error("web_http_"+response.status);const html=await response.text();const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g,"").trim()??current.hostname;return{url:current.toString(),title,text:stripHtml(html).slice(0,100000)};}throw new Error("web_too_many_redirects");}
 async search(query:string){const safe=await assertSafeUrl("https://html.duckduckgo.com/html/?q="+encodeURIComponent(query));const response=await fetch(safe,{signal:AbortSignal.timeout(config.webTimeoutMs),headers:{"user-agent":"Morok/1.0"}});if(!response.ok)throw new Error("web_search_http_"+response.status);const html=await response.text();const results:Array<{title:string;url:string;snippet:string}>=[];const re=/<a[^>]+class="result__a"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<a[^>]+class="result__snippet"[^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))&&results.length<10)results.push({url:m[1]??"",title:stripHtml(m[2]??""),snippet:stripHtml(m[3]??"")});return results;}
}