import type { FastifyInstance, FastifyRequest } from "fastify";
import { connectDatabase } from "./db.js";
import { AuthService } from "./domain/auth.js";
import { SessionService } from "./domain/session.js";
import { VaultService } from "./domain/vault.js";
import { DocumentService, type DocumentFormat } from "./domain/documents.js";
import { CommunicationService, type Integration } from "./domain/communications.js";
import { PlannerService } from "./domain/planner.js";
import { AutomationService } from "./domain/automation.js";
async function auth(req:FastifyRequest){const header=req.headers.authorization;if(!header?.startsWith("Bearer "))return null;const db=await connectDatabase();const token=header.slice(7);const user=await new AuthService(db).authenticate(token);if(!user)return null;const session=await new SessionService(db).getByToken(token);return session&&session.userId===user.id?{user,session}:null;}
export async function registerPhase1Routes(app:FastifyInstance){
 app.get("/api/v1/planner/today",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});return new PlannerService(await connectDatabase()).today(a.user.id);});
 app.get("/api/v1/automations/:id/runs",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const id=(req.params as {id:string}).id;return {runs:await (await connectDatabase()).collection("audit_logs").find({actorId:a.user.id,automationId:id}).sort({createdAt:-1}).limit(100).toArray()};});
 app.delete("/api/v1/tasks/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const id=(req.params as {id:string}).id;const r=await (await connectDatabase()).collection("tasks").deleteOne({id,userId:a.user.id});return r.deletedCount?{ok:true}:reply.code(404).send({error:"task_not_found"});});
 app.post("/api/v1/tasks/:id/complete",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const id=(req.params as {id:string}).id;const r=await (await connectDatabase()).collection("tasks").findOneAndUpdate({id,userId:a.user.id},{$set:{status:"completed",updatedAt:new Date()}},{returnDocument:"after"});return r?{task:r}:reply.code(404).send({error:"task_not_found"});});
 app.get("/api/v1/vault",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});return {secrets:await new VaultService(await connectDatabase()).list(a.user.id)};});
 app.post("/api/v1/vault",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {name?:string;kind?:string;value?:string};if(!b?.name||!b.value)return reply.code(400).send({error:"name_and_value_required"});try{return reply.code(201).send({secret:await new VaultService(await connectDatabase()).set(a.user.id,b.name,b.kind??"generic",b.value)});}catch(e){if(e instanceof Error&&e.message==="vault_key_not_configured")return reply.code(503).send({error:e.message});throw e;}});
 app.delete("/api/v1/vault/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const ok=await new VaultService(await connectDatabase()).remove(a.user.id,(req.params as {id:string}).id);return ok?{ok:true}:reply.code(404).send({error:"secret_not_found"});});
 app.get("/api/v1/documents",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});return {documents:await new DocumentService(await connectDatabase()).list(a.user.id)};});
 app.post("/api/v1/documents",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {name?:string;format?:DocumentFormat;content?:string};if(!b?.name||!b.format||typeof b.content!=="string"||!["text","markdown","json","csv","html"].includes(b.format))return reply.code(400).send({error:"invalid_document"});return reply.code(201).send({document:await new DocumentService(await connectDatabase()).create(a.user.id,b.name,b.format,b.content)});});
 app.get("/api/v1/documents/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const d=await new DocumentService(await connectDatabase()).get(a.user.id,(req.params as {id:string}).id);return d?{document:d}:reply.code(404).send({error:"document_not_found"});});
 app.patch("/api/v1/documents/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {name?:string;format?:DocumentFormat;content?:string};const d=await new DocumentService(await connectDatabase()).update(a.user.id,(req.params as {id:string}).id,b);return d?{document:d}:reply.code(404).send({error:"document_not_found"});});
 app.delete("/api/v1/documents/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const ok=await new DocumentService(await connectDatabase()).remove(a.user.id,(req.params as {id:string}).id);return ok?{ok:true}:reply.code(404).send({error:"document_not_found"});});
 app.get("/api/v1/integrations",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});return {integrations:await new CommunicationService(await connectDatabase()).list(a.user.id)};});
 app.post("/api/v1/integrations",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {type?:Integration["type"];name?:string;endpoint?:string;secret?:string};if(!b?.type||!b.name||!b.endpoint||!b.secret)return reply.code(400).send({error:"integration_fields_required"});try{return reply.code(201).send({integration:await new CommunicationService(await connectDatabase()).create(a.user.id,b.type,b.name,b.endpoint,b.secret)});}catch(e){return reply.code(400).send({error:e instanceof Error?e.message:"integration_failed"});}});
 app.patch("/api/v1/integrations/:id",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {enabled?:boolean};if(typeof b.enabled!=="boolean")return reply.code(400).send({error:"enabled_required"});const i=await new CommunicationService(await connectDatabase()).setEnabled(a.user.id,(req.params as {id:string}).id,b.enabled);return i?{integration:i}:reply.code(404).send({error:"integration_not_found"});});
 app.post("/api/v1/integrations/:id/send",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});const b=req.body as {message?:string};if(!b?.message?.trim())return reply.code(400).send({error:"message_required"});try{return await new CommunicationService(await connectDatabase()).send(a.user.id,(req.params as {id:string}).id,b.message);}catch(e){return reply.code(400).send({error:e instanceof Error?e.message:"send_failed"});}});
 app.get("/api/v1/capabilities",async(req,reply)=>{const a=await auth(req);if(!a)return reply.code(401).send({error:"unauthorized"});return {phase:1,status:"complete",capabilities:["chat","conversation-history","memory","tasks","calendar","contacts","notifications","files","documents","web-search","web-open","streaming","voice-input","voice-output","automation-scheduler","planning","credential-vault","integrations","audit"]};});
}
