import { buildApp } from "./app.js";
import { closeDatabase, connectDatabase } from "./db.js";
import { config } from "./config.js";
import { AutomationScheduler } from "./domain/scheduler.js";
const app=await buildApp();
const db=await connectDatabase();
const scheduler=new AutomationScheduler(db);scheduler.start(15000);
const shutdown=async()=>{scheduler.stop();await app.close();await closeDatabase();};
process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
await app.listen({host:config.host,port:config.port});